parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''

api_platform:
    title: 'School Certs platform API'
    description: 'API for student archive to generate and print scholar certificates'
    version: 1.0.0
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/api_platform'

    # FOSUserBundle integration.
#    enable_fos_user: true
    # Swagger
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    # Enable the Varnish integration
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true
